// from http://www.gilscottheron.com/lyrevol.html
lyrics = ["You will not be able to stay home, brother.",
"You will not be able to plug in, turn on and cop out.",
"You will not be able to lose yourself on skag and skip out for beer during commercials,",
"Because the revolution will not be televised.",

"The revolution will not be televised.",
"The revolution will not be brought to you by Xerox",
"In 4 parts without commercial interruptions.",
"The revolution will not show you pictures of Nixon",
"blowing a bugle and leading a charge by John",
"Mitchell, General Abrams and Spiro Agnew to eat",
"hog maws confiscated from a Harlem sanctuary.",
"The revolution will not be televised.",

"The revolution will not be brought to you by the ",
"Schaefer Award Theatre and will not star Natalie",
"Woods and Steve McQueen or Bullwinkle and Julia.",
"The revolution will not give your mouth sex appeal.",
"The revolution will not get rid of the nubs.",
"The revolution will not make you look five pounds",
"thinner, because the revolution will not be televised, Brother.",

"There will be no pictures of you and Willie May",
"pushing that shopping cart down the block on the dead run,",
"or trying to slide that color television into a stolen ambulance.",
"NBC will not be able predict the winner at 8:32",
"or report from 29 districts.",
"The revolution will not be televised.",

"There will be no pictures of pigs shooting down",
"brothers in the instant replay.",
"There will be no pictures of pigs shooting down",
"brothers in the instant replay.",
"There will be no pictures of Whitney Young being",
"run out of Harlem on a rail with a brand new process.",
"There will be no slow motion or still life of Roy",
"Wilkens strolling through Watts in a Red, Black and",
"Green liberation jumpsuit that he had been saving",
"For just the proper occasion.",

"Green Acres, The Beverly Hillbillies, and Hooterville",
"Junction will no longer be so damned relevant, and",
"women will not care if Dick finally gets down with",
"Jane on Search for Tomorrow because Black people",
"will be in the street looking for a brighter day.",
"The revolution will not be televised.",

"There will be no highlights on the eleven o'clock",
"news and no pictures of hairy armed women",
"liberationists and Jackie Onassis blowing her nose.",
"The theme song will not be written by Jim Webb,",
"Francis Scott Key, nor sung by Glen Campbell, Tom",
"Jones, Johnny Cash, Englebert Humperdink, or the Rare Earth.",
"The revolution will not be televised.",

"The revolution will not be right back after a message",
"bbout a white tornado, white lightning, or white people.",
"You will not have to worry about a dove in your",
"bedroom, a tiger in your tank, or the giant in your toilet bowl.",
"The revolution will not go better with Coke.",
"The revolution will not fight the germs that may cause bad breath.",
"The revolution will put you in the driver's seat.",

"The revolution will not be televised, will not be televised,",
"will not be televised, will not be televised.",
"The revolution will be no re-run brothers;",
"The revolution will be live."];
